### PR TITLE
Add @theia/electron dependency to the example electron app

### LINKED ISSUE #29: make sure that @theia/electron is installed
We should do it after 0.6.0 release.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #29

**Description**
- Added the `@theia/electron` to the example electron app so that the electron app can be properly built.
- Refactored `app-package.json` template to `app-browser-package.json` and `app-electron-package.json`.

**How to Test**
1. clone the repository, and checkout the PR branch.
2. perform `npm link` on the root of the repository.
3. create a temporary folder in your filesystem, and navigate to it.
4. perform `yo theia-extension` to generate the extension (choose a name when prompted).
5. perform `(yarn && yarn rebuild:electron`).
6. perform `(cd electron-app && yarn start)`.
7. ensure that the electron app starts.

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@akosyakov 
I wasn't able to successfully add the **key-value** pair in the json without encountering syntax errors.
My original idea was to perform a check for `params.electron` and only then add the new `@theia/electron` dependency.

Instead, I opted for the simpler approach and refactored the `app-package.json` into `app-browser-package.json` and `app-electron-package.json`.

**Comment by akosyakov** [comment]
@vince-fugnitto Can you publish a new release afterwards?

**Comment by marcdumais-work** [comment]
> @vince-fugnitto Can you publish a new release afterwards?

I can take care of it.

**Comment by vince-fugnitto** [comment]
> > @vince-fugnitto Can you publish a new release afterwards?
> 
> I can take care of it.

Thank you!

**Comment by marcdumais-work** [comment]
merging

**Comment by marcdumais-work** [comment]
published v0.1.13

**Pull request merged**
