### PR TITLE
Remove deprecated extensions

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Removes deprecated extensions from both the `browser` and `electron` examples.

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@akosyakov we'd need to release the update so issues such as https://github.com/eclipse-theia/theia/issues/7248 do not occur for users.

**Comment by vince-fugnitto** [comment]
> looks good

Thank you! Would it be possible to do a release?

**Comment by marcdumais-work** [comment]
> Thank you! Would it be possible to do a release?

Yes, I will do it

**Comment by vince-fugnitto** [comment]
> > Thank you! Would it be possible to do a release?
> 
> Yes, I will do it

Thank you @marcdumais-work!

**Comment by marcdumais-work** [comment]
Done. @vince-fugnitto would you give a try from a fresh version pulled from npm?

**Comment by vince-fugnitto** [comment]
> Done. @vince-fugnitto would you give a try from a fresh version pulled from npm?

It worked correctly, thank you!

**Pull request merged**
